# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(734, 694)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 701, 531))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_dashboard = QtWidgets.QWidget()
        self.tab_dashboard.setObjectName("tab_dashboard")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_dashboard)
        self.calendarWidget.setGeometry(QtCore.QRect(390, 10, 280, 173))
        self.calendarWidget.setObjectName("calendarWidget")
        self.tabWidget.addTab(self.tab_dashboard, "")
        self.tab_stakeholder = QtWidgets.QWidget()
        self.tab_stakeholder.setObjectName("tab_stakeholder")
        self.tableWidget_party = QtWidgets.QTableWidget(self.tab_stakeholder)
        self.tableWidget_party.setGeometry(QtCore.QRect(20, 90, 661, 411))
        self.tableWidget_party.setObjectName("tableWidget_party")
        self.tableWidget_party.setColumnCount(0)
        self.tableWidget_party.setRowCount(0)
        self.tabWidget.addTab(self.tab_stakeholder, "")
        self.tab_inventory = QtWidgets.QWidget()
        self.tab_inventory.setObjectName("tab_inventory")
        self.tableWidget_inventory = QtWidgets.QTableWidget(self.tab_inventory)
        self.tableWidget_inventory.setGeometry(QtCore.QRect(10, 80, 671, 421))
        self.tableWidget_inventory.setObjectName("tableWidget_inventory")
        self.tableWidget_inventory.setColumnCount(0)
        self.tableWidget_inventory.setRowCount(0)
        self.tabWidget.addTab(self.tab_inventory, "")
        self.tab_Transaction = QtWidgets.QWidget()
        self.tab_Transaction.setObjectName("tab_Transaction")
        self.tab_trans = QtWidgets.QTabWidget(self.tab_Transaction)
        self.tab_trans.setGeometry(QtCore.QRect(10, 10, 651, 501))
        self.tab_trans.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_trans.setObjectName("tab_trans")
        self.tab_trans_Sale = QtWidgets.QWidget()
        self.tab_trans_Sale.setObjectName("tab_trans_Sale")
        self.tab_trans.addTab(self.tab_trans_Sale, "")
        self.tab_trans_Purchase = QtWidgets.QWidget()
        self.tab_trans_Purchase.setObjectName("tab_trans_Purchase")
        self.tab_trans.addTab(self.tab_trans_Purchase, "")
        self.tab_trans_General = QtWidgets.QWidget()
        self.tab_trans_General.setObjectName("tab_trans_General")
        self.tab_trans.addTab(self.tab_trans_General, "")
        self.tab_trans_All = QtWidgets.QWidget()
        self.tab_trans_All.setObjectName("tab_trans_All")
        self.tableWidget_transaction = QtWidgets.QTableWidget(self.tab_trans_All)
        self.tableWidget_transaction.setGeometry(QtCore.QRect(10, 60, 631, 401))
        self.tableWidget_transaction.setObjectName("tableWidget_transaction")
        self.tableWidget_transaction.setColumnCount(0)
        self.tableWidget_transaction.setRowCount(0)
        self.tab_trans.addTab(self.tab_trans_All, "")
        self.tabWidget.addTab(self.tab_Transaction, "")
        self.tab_admin = QtWidgets.QWidget()
        self.tab_admin.setObjectName("tab_admin")
        self.tabWidget.addTab(self.tab_admin, "")
        self.label_Tab_Title = QtWidgets.QLabel(self.centralwidget)
        self.label_Tab_Title.setGeometry(QtCore.QRect(40, 30, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_Tab_Title.setFont(font)
        self.label_Tab_Title.setObjectName("label_Tab_Title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 734, 21))
        self.menubar.setObjectName("menubar")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        self.menuBackup = QtWidgets.QMenu(self.menubar)
        self.menuBackup.setObjectName("menuBackup")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionUpdateRecord = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Edit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdateRecord.setIcon(icon)
        self.actionUpdateRecord.setObjectName("actionUpdateRecord")
        self.actionNewRecord = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/add"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewRecord.setIcon(icon1)
        self.actionNewRecord.setObjectName("actionNewRecord")
        self.actionFilterRecord = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/Filter"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFilterRecord.setIcon(icon2)
        self.actionFilterRecord.setObjectName("actionFilterRecord")
        self.actionDeleteRecord = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/delete"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteRecord.setIcon(icon3)
        self.actionDeleteRecord.setObjectName("actionDeleteRecord")
        self.actionRollback = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/cancel"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRollback.setIcon(icon4)
        self.actionRollback.setObjectName("actionRollback")
        self.actionCommit = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/Save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCommit.setIcon(icon5)
        self.actionCommit.setObjectName("actionCommit")
        self.actionTake_Backup = QtWidgets.QAction(MainWindow)
        self.actionTake_Backup.setObjectName("actionTake_Backup")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionRestore_Backup = QtWidgets.QAction(MainWindow)
        self.actionRestore_Backup.setObjectName("actionRestore_Backup")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuAction.addAction(self.actionNewRecord)
        self.menuAction.addAction(self.actionUpdateRecord)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionFilterRecord)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionDeleteRecord)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionRollback)
        self.menuAction.addAction(self.actionCommit)
        self.menuBackup.addAction(self.actionTake_Backup)
        self.menuBackup.addAction(self.actionRestore_Backup)
        self.menuBackup.addSeparator()
        self.menuBackup.addAction(self.actionExport)
        self.menuBackup.addAction(self.actionImport)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuAction.menuAction())
        self.menubar.addAction(self.menuBackup.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNewRecord)
        self.toolBar.addAction(self.actionUpdateRecord)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFilterRecord)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCommit)
        self.toolBar.addAction(self.actionRollback)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.tab_trans.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hisaab-Kitaab V1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dashboard), _translate("MainWindow", "Dashboard"))
        self.tableWidget_party.setSortingEnabled(False)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_stakeholder), _translate("MainWindow", "Stakeholder"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_inventory), _translate("MainWindow", "Inventory"))
        self.tab_trans.setTabText(self.tab_trans.indexOf(self.tab_trans_Sale), _translate("MainWindow", "Sale"))
        self.tab_trans.setTabText(self.tab_trans.indexOf(self.tab_trans_Purchase), _translate("MainWindow", "Purchase"))
        self.tab_trans.setTabText(self.tab_trans.indexOf(self.tab_trans_General), _translate("MainWindow", "General"))
        self.tab_trans.setTabText(self.tab_trans.indexOf(self.tab_trans_All), _translate("MainWindow", "All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Transaction), _translate("MainWindow", "Transaction"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_admin), _translate("MainWindow", "Admin"))
        self.label_Tab_Title.setText(_translate("MainWindow", "Title of Tab"))
        self.menuAction.setTitle(_translate("MainWindow", "Action"))
        self.menuBackup.setTitle(_translate("MainWindow", "Backup"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionUpdateRecord.setText(_translate("MainWindow", "Update"))
        self.actionUpdateRecord.setToolTip(_translate("MainWindow", "Update Record"))
        self.actionUpdateRecord.setStatusTip(_translate("MainWindow", "Update Record"))
        self.actionUpdateRecord.setWhatsThis(_translate("MainWindow", "Update Record"))
        self.actionNewRecord.setText(_translate("MainWindow", "New"))
        self.actionFilterRecord.setText(_translate("MainWindow", "Filter"))
        self.actionFilterRecord.setToolTip(_translate("MainWindow", "Filter Records"))
        self.actionFilterRecord.setStatusTip(_translate("MainWindow", "Filter Records"))
        self.actionFilterRecord.setWhatsThis(_translate("MainWindow", "Filter Records"))
        self.actionDeleteRecord.setText(_translate("MainWindow", "Delete"))
        self.actionRollback.setText(_translate("MainWindow", "Rollback"))
        self.actionCommit.setText(_translate("MainWindow", "Commit"))
        self.actionTake_Backup.setText(_translate("MainWindow", "Take Backup"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionRestore_Backup.setText(_translate("MainWindow", "Restore Backup"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
import res_main_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
