# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Tab_Title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_Tab_Title.setFont(font)
        self.label_Tab_Title.setObjectName("label_Tab_Title")
        self.verticalLayout.addWidget(self.label_Tab_Title)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Transaction = QtWidgets.QWidget()
        self.tab_Transaction.setObjectName("tab_Transaction")
        self.tab_trans = QtWidgets.QTabWidget(self.tab_Transaction)
        self.tab_trans.setGeometry(QtCore.QRect(10, 10, 811, 561))
        self.tab_trans.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_trans.setObjectName("tab_trans")
        self.tab_trans_Sale = QtWidgets.QWidget()
        self.tab_trans_Sale.setObjectName("tab_trans_Sale")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_trans_Sale)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 481, 91))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_trans_sale_StakeholderName = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_trans_sale_StakeholderName.setEnabled(True)
        self.lineEdit_trans_sale_StakeholderName.setGeometry(QtCore.QRect(180, 60, 291, 22))
        self.lineEdit_trans_sale_StakeholderName.setText("")
        self.lineEdit_trans_sale_StakeholderName.setReadOnly(True)
        self.lineEdit_trans_sale_StakeholderName.setObjectName("lineEdit_trans_sale_StakeholderName")
        self.label_trans_sale_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_trans_sale_12.setGeometry(QtCore.QRect(28, 30, 61, 20))
        self.label_trans_sale_12.setObjectName("label_trans_sale_12")
        self.label_trans_sale_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_trans_sale_14.setGeometry(QtCore.QRect(240, 30, 71, 20))
        self.label_trans_sale_14.setObjectName("label_trans_sale_14")
        self.lineEdit_trans_sale_timestamp = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_trans_sale_timestamp.setGeometry(QtCore.QRect(320, 30, 151, 22))
        self.lineEdit_trans_sale_timestamp.setObjectName("lineEdit_trans_sale_timestamp")
        self.label_trans_sale_01 = QtWidgets.QLabel(self.groupBox_5)
        self.label_trans_sale_01.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_trans_sale_01.setObjectName("label_trans_sale_01")
        self.lineEdit_trans_sale_InvoiceNumber = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_trans_sale_InvoiceNumber.setGeometry(QtCore.QRect(90, 30, 101, 22))
        self.lineEdit_trans_sale_InvoiceNumber.setObjectName("lineEdit_trans_sale_InvoiceNumber")
        self.lineEdit_trans_sale_StakeholderID = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_trans_sale_StakeholderID.setGeometry(QtCore.QRect(90, 60, 61, 22))
        self.lineEdit_trans_sale_StakeholderID.setObjectName("lineEdit_trans_sale_StakeholderID")
        self.pushButton_trans_addInvoice_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_trans_addInvoice_2.setGeometry(QtCore.QRect(150, 60, 21, 22))
        self.pushButton_trans_addInvoice_2.setObjectName("pushButton_trans_addInvoice_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_trans_Sale)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 150, 481, 341))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_trans_sale_trans_id = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_trans_sale_trans_id.setGeometry(QtCore.QRect(380, 20, 81, 22))
        self.lineEdit_trans_sale_trans_id.setText("")
        self.lineEdit_trans_sale_trans_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_trans_sale_trans_id.setObjectName("lineEdit_trans_sale_trans_id")
        self.label_trans_sale_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_trans_sale_13.setGeometry(QtCore.QRect(38, 20, 31, 20))
        self.label_trans_sale_13.setObjectName("label_trans_sale_13")
        self.label_trans_sale_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_trans_sale_15.setGeometry(QtCore.QRect(320, 20, 51, 16))
        self.label_trans_sale_15.setObjectName("label_trans_sale_15")
        self.lineEdit_trans_sale_ItemID = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_trans_sale_ItemID.setGeometry(QtCore.QRect(80, 49, 71, 22))
        self.lineEdit_trans_sale_ItemID.setText("")
        self.lineEdit_trans_sale_ItemID.setObjectName("lineEdit_trans_sale_ItemID")
        self.label_trans_sale_02 = QtWidgets.QLabel(self.groupBox_6)
        self.label_trans_sale_02.setGeometry(QtCore.QRect(40, 50, 27, 16))
        self.label_trans_sale_02.setObjectName("label_trans_sale_02")
        self.label_trans_sale_03 = QtWidgets.QLabel(self.groupBox_6)
        self.label_trans_sale_03.setGeometry(QtCore.QRect(30, 80, 42, 16))
        self.label_trans_sale_03.setObjectName("label_trans_sale_03")
        self.lineEdit_trans_sale_Item_details = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_trans_sale_Item_details.setGeometry(QtCore.QRect(80, 80, 381, 22))
        self.lineEdit_trans_sale_Item_details.setText("")
        self.lineEdit_trans_sale_Item_details.setObjectName("lineEdit_trans_sale_Item_details")
        self.lineEdit_trans_sale_unit = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_trans_sale_unit.setGeometry(QtCore.QRect(209, 113, 111, 22))
        self.lineEdit_trans_sale_unit.setText("")
        self.lineEdit_trans_sale_unit.setObjectName("lineEdit_trans_sale_unit")
        self.lineEdit_trans_sale_quantity = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_trans_sale_quantity.setGeometry(QtCore.QRect(78, 113, 61, 22))
        self.lineEdit_trans_sale_quantity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_trans_sale_quantity.setObjectName("lineEdit_trans_sale_quantity")
        self.label_trans_sale_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_trans_sale_5.setGeometry(QtCore.QRect(180, 113, 25, 16))
        self.label_trans_sale_5.setObjectName("label_trans_sale_5")
        self.label_trans_sale_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_trans_sale_4.setGeometry(QtCore.QRect(20, 110, 52, 16))
        self.label_trans_sale_4.setObjectName("label_trans_sale_4")
        self.lineEdit_trans_sale_total = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_trans_sale_total.setGeometry(QtCore.QRect(370, 140, 71, 22))
        self.lineEdit_trans_sale_total.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_trans_sale_total.setObjectName("lineEdit_trans_sale_total")
        self.label_trans_sale_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_trans_sale_7.setGeometry(QtCore.QRect(335, 140, 35, 16))
        self.label_trans_sale_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_trans_sale_7.setScaledContents(False)
        self.label_trans_sale_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_trans_sale_7.setObjectName("label_trans_sale_7")
        self.label_trans_sale_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_trans_sale_6.setGeometry(QtCore.QRect(40, 140, 28, 16))
        self.label_trans_sale_6.setObjectName("label_trans_sale_6")
        self.lineEdit_trans_sale_rate = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_trans_sale_rate.setGeometry(QtCore.QRect(80, 140, 61, 22))
        self.lineEdit_trans_sale_rate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_trans_sale_rate.setObjectName("lineEdit_trans_sale_rate")
        self.lineEdit_trans_sale_cash = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_trans_sale_cash.setGeometry(QtCore.QRect(80, 170, 110, 22))
        self.lineEdit_trans_sale_cash.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_trans_sale_cash.setObjectName("lineEdit_trans_sale_cash")
        self.label_trans_sale_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_trans_sale_21.setGeometry(QtCore.QRect(40, 170, 31, 16))
        self.label_trans_sale_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_trans_sale_21.setScaledContents(False)
        self.label_trans_sale_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_trans_sale_21.setObjectName("label_trans_sale_21")
        self.lineEdit_trans_sale_schedule = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_trans_sale_schedule.setGeometry(QtCore.QRect(270, 199, 110, 22))
        self.lineEdit_trans_sale_schedule.setObjectName("lineEdit_trans_sale_schedule")
        self.label_trans_sale_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_trans_sale_9.setGeometry(QtCore.QRect(207, 200, 57, 16))
        self.label_trans_sale_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_trans_sale_9.setScaledContents(False)
        self.label_trans_sale_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_trans_sale_9.setObjectName("label_trans_sale_9")
        self.lineEdit_trans_sale_credit = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_trans_sale_credit.setGeometry(QtCore.QRect(80, 199, 111, 21))
        self.lineEdit_trans_sale_credit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_trans_sale_credit.setObjectName("lineEdit_trans_sale_credit")
        self.label_trans_sale_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_trans_sale_8.setGeometry(QtCore.QRect(30, 199, 38, 16))
        self.label_trans_sale_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_trans_sale_8.setScaledContents(False)
        self.label_trans_sale_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_trans_sale_8.setObjectName("label_trans_sale_8")
        self.lineEdit_trans_sale_terms = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_trans_sale_terms.setGeometry(QtCore.QRect(79, 229, 301, 22))
        self.lineEdit_trans_sale_terms.setObjectName("lineEdit_trans_sale_terms")
        self.label_trans_sale_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_trans_sale_10.setGeometry(QtCore.QRect(30, 230, 39, 16))
        self.label_trans_sale_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_trans_sale_10.setScaledContents(False)
        self.label_trans_sale_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_trans_sale_10.setObjectName("label_trans_sale_10")
        self.label_trans_sale_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_trans_sale_11.setGeometry(QtCore.QRect(30, 260, 36, 16))
        self.label_trans_sale_11.setObjectName("label_trans_sale_11")
        self.lineEdit_trans_sale_notes = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_trans_sale_notes.setGeometry(QtCore.QRect(80, 270, 381, 51))
        self.lineEdit_trans_sale_notes.setObjectName("lineEdit_trans_sale_notes")
        self.pushButton_trans_addInvoice_3 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_trans_addInvoice_3.setGeometry(QtCore.QRect(150, 50, 21, 22))
        self.pushButton_trans_addInvoice_3.setObjectName("pushButton_trans_addInvoice_3")
        self.lineEdit_trans_sale_ItemName = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_trans_sale_ItemName.setEnabled(True)
        self.lineEdit_trans_sale_ItemName.setGeometry(QtCore.QRect(180, 50, 281, 22))
        self.lineEdit_trans_sale_ItemName.setText("")
        self.lineEdit_trans_sale_ItemName.setReadOnly(True)
        self.lineEdit_trans_sale_ItemName.setObjectName("lineEdit_trans_sale_ItemName")
        self.lineEdit_trans_sale_TransactionType = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_trans_sale_TransactionType.setGeometry(QtCore.QRect(80, 20, 113, 22))
        self.lineEdit_trans_sale_TransactionType.setObjectName("lineEdit_trans_sale_TransactionType")
        self.toolBox_trans_SalePurchase = QtWidgets.QToolBox(self.tab_trans_Sale)
        self.toolBox_trans_SalePurchase.setGeometry(QtCore.QRect(530, 20, 241, 451))
        self.toolBox_trans_SalePurchase.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolBox_trans_SalePurchase.setObjectName("toolBox_trans_SalePurchase")
        self.page_Invoice = QtWidgets.QWidget()
        self.page_Invoice.setGeometry(QtCore.QRect(0, 0, 237, 387))
        self.page_Invoice.setObjectName("page_Invoice")
        self.toolBox_trans_SalePurchase.addItem(self.page_Invoice, "")
        self.page_History = QtWidgets.QWidget()
        self.page_History.setGeometry(QtCore.QRect(0, 0, 237, 387))
        self.page_History.setObjectName("page_History")
        self.treeWidget_trans = QtWidgets.QTreeWidget(self.page_History)
        self.treeWidget_trans.setGeometry(QtCore.QRect(10, 20, 211, 341))
        self.treeWidget_trans.setObjectName("treeWidget_trans")
        self.treeWidget_trans.headerItem().setText(0, "1")
        self.toolBox_trans_SalePurchase.addItem(self.page_History, "")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_trans_Sale)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 110, 201, 41))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_trans_new = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_trans_new.setGeometry(QtCore.QRect(10, 10, 41, 26))
        self.pushButton_trans_new.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Add"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_trans_new.setIcon(icon)
        self.pushButton_trans_new.setObjectName("pushButton_trans_new")
        self.pushButton_trans_duplicate = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_trans_duplicate.setGeometry(QtCore.QRect(60, 10, 41, 26))
        self.pushButton_trans_duplicate.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/Duplicate"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_trans_duplicate.setIcon(icon1)
        self.pushButton_trans_duplicate.setObjectName("pushButton_trans_duplicate")
        self.pushButton_trans_save = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_trans_save.setGeometry(QtCore.QRect(130, 10, 41, 26))
        self.pushButton_trans_save.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/Save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_trans_save.setIcon(icon2)
        self.pushButton_trans_save.setObjectName("pushButton_trans_save")
        self.tab_trans.addTab(self.tab_trans_Sale, "")
        self.tab_trans_General = QtWidgets.QWidget()
        self.tab_trans_General.setObjectName("tab_trans_General")
        self.tab_trans.addTab(self.tab_trans_General, "")
        self.tab_trans_All = QtWidgets.QWidget()
        self.tab_trans_All.setObjectName("tab_trans_All")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_trans_All)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_trans_All)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_trans_All)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_trans_All)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 1, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_trans_All)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.tableWidget_transaction = QtWidgets.QTableWidget(self.tab_trans_All)
        self.tableWidget_transaction.setObjectName("tableWidget_transaction")
        self.tableWidget_transaction.setColumnCount(0)
        self.tableWidget_transaction.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_transaction)
        self.tab_trans.addTab(self.tab_trans_All, "")
        self.tabWidget.addTab(self.tab_Transaction, "")
        self.tab_stakeholder = QtWidgets.QWidget()
        self.tab_stakeholder.setObjectName("tab_stakeholder")
        self.tableWidget_stk = QtWidgets.QTableWidget(self.tab_stakeholder)
        self.tableWidget_stk.setGeometry(QtCore.QRect(30, 170, 851, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_stk.sizePolicy().hasHeightForWidth())
        self.tableWidget_stk.setSizePolicy(sizePolicy)
        self.tableWidget_stk.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_stk.setObjectName("tableWidget_stk")
        self.tableWidget_stk.setColumnCount(0)
        self.tableWidget_stk.setRowCount(0)
        self.groupBox = QtWidgets.QGroupBox(self.tab_stakeholder)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 781, 131))
        self.groupBox.setTitle("")
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_Stk_ID_ReminderDateTime = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Stk_ID_ReminderDateTime.setGeometry(QtCore.QRect(680, 50, 71, 22))
        self.lineEdit_Stk_ID_ReminderDateTime.setObjectName("lineEdit_Stk_ID_ReminderDateTime")
        self.label_Stk_01 = QtWidgets.QLabel(self.groupBox)
        self.label_Stk_01.setGeometry(QtCore.QRect(50, 10, 16, 16))
        self.label_Stk_01.setObjectName("label_Stk_01")
        self.checkBox_IsCustomer = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_IsCustomer.setGeometry(QtCore.QRect(130, 10, 86, 21))
        self.checkBox_IsCustomer.setObjectName("checkBox_IsCustomer")
        self.lineEdit_Stk_AmountPayable = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Stk_AmountPayable.setGeometry(QtCore.QRect(530, 20, 71, 22))
        self.lineEdit_Stk_AmountPayable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Stk_AmountPayable.setObjectName("lineEdit_Stk_AmountPayable")
        self.checkBox_IsSupplier = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_IsSupplier.setGeometry(QtCore.QRect(220, 10, 81, 21))
        self.checkBox_IsSupplier.setObjectName("checkBox_IsSupplier")
        self.label_Stk_10 = QtWidgets.QLabel(self.groupBox)
        self.label_Stk_10.setGeometry(QtCore.QRect(30, 100, 41, 16))
        self.label_Stk_10.setObjectName("label_Stk_10")
        self.label_Stk_12 = QtWidgets.QLabel(self.groupBox)
        self.label_Stk_12.setGeometry(QtCore.QRect(620, 50, 61, 16))
        self.label_Stk_12.setObjectName("label_Stk_12")
        self.label_Stk_11 = QtWidgets.QLabel(self.groupBox)
        self.label_Stk_11.setGeometry(QtCore.QRect(620, 20, 61, 16))
        self.label_Stk_11.setObjectName("label_Stk_11")
        self.label_Stk_03 = QtWidgets.QLabel(self.groupBox)
        self.label_Stk_03.setGeometry(QtCore.QRect(20, 70, 51, 16))
        self.label_Stk_03.setObjectName("label_Stk_03")
        self.label_Stk_08 = QtWidgets.QLabel(self.groupBox)
        self.label_Stk_08.setGeometry(QtCore.QRect(470, 20, 51, 16))
        self.label_Stk_08.setObjectName("label_Stk_08")
        self.checkBox_IsEmployee = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_IsEmployee.setGeometry(QtCore.QRect(300, 10, 86, 21))
        self.checkBox_IsEmployee.setObjectName("checkBox_IsEmployee")
        self.lineEdit_Stk_Notes = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Stk_Notes.setGeometry(QtCore.QRect(70, 100, 681, 22))
        self.lineEdit_Stk_Notes.setObjectName("lineEdit_Stk_Notes")
        self.lineEdit_Stk_StakeholderID = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Stk_StakeholderID.setGeometry(QtCore.QRect(70, 10, 51, 22))
        self.lineEdit_Stk_StakeholderID.setObjectName("lineEdit_Stk_StakeholderID")
        self.lineEdit_Stk_StakeholderName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Stk_StakeholderName.setGeometry(QtCore.QRect(70, 40, 361, 22))
        self.lineEdit_Stk_StakeholderName.setObjectName("lineEdit_Stk_StakeholderName")
        self.label_Stk_02 = QtWidgets.QLabel(self.groupBox)
        self.label_Stk_02.setGeometry(QtCore.QRect(30, 40, 36, 16))
        self.label_Stk_02.setObjectName("label_Stk_02")
        self.lineEdit_Stk_ReminderNote = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Stk_ReminderNote.setGeometry(QtCore.QRect(680, 20, 71, 22))
        self.lineEdit_Stk_ReminderNote.setObjectName("lineEdit_Stk_ReminderNote")
        self.lineEdit_Stk_AmountReceivable = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Stk_AmountReceivable.setGeometry(QtCore.QRect(530, 50, 71, 22))
        self.lineEdit_Stk_AmountReceivable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Stk_AmountReceivable.setObjectName("lineEdit_Stk_AmountReceivable")
        self.label_Stk_09 = QtWidgets.QLabel(self.groupBox)
        self.label_Stk_09.setGeometry(QtCore.QRect(460, 50, 71, 16))
        self.label_Stk_09.setObjectName("label_Stk_09")
        self.lineEdit_Stk_ContactInfo = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Stk_ContactInfo.setGeometry(QtCore.QRect(70, 70, 361, 22))
        self.lineEdit_Stk_ContactInfo.setObjectName("lineEdit_Stk_ContactInfo")
        self.lineEdit_search_tableWidget_stk = QtWidgets.QLineEdit(self.tab_stakeholder)
        self.lineEdit_search_tableWidget_stk.setGeometry(QtCore.QRect(100, 500, 311, 22))
        self.lineEdit_search_tableWidget_stk.setObjectName("lineEdit_search_tableWidget_stk")
        self.label_stk_search = QtWidgets.QLabel(self.tab_stakeholder)
        self.label_stk_search.setGeometry(QtCore.QRect(30, 500, 60, 16))
        self.label_stk_search.setObjectName("label_stk_search")
        self.pushButton_search_prev_tableWidget_stk = QtWidgets.QPushButton(self.tab_stakeholder)
        self.pushButton_search_prev_tableWidget_stk.setGeometry(QtCore.QRect(430, 500, 51, 26))
        self.pushButton_search_prev_tableWidget_stk.setObjectName("pushButton_search_prev_tableWidget_stk")
        self.pushButton_search_next_tableWidget_stk = QtWidgets.QPushButton(self.tab_stakeholder)
        self.pushButton_search_next_tableWidget_stk.setGeometry(QtCore.QRect(490, 500, 51, 26))
        self.pushButton_search_next_tableWidget_stk.setObjectName("pushButton_search_next_tableWidget_stk")
        self.label_search_status_tableWidget_stk = QtWidgets.QLabel(self.tab_stakeholder)
        self.label_search_status_tableWidget_stk.setGeometry(QtCore.QRect(550, 500, 60, 21))
        self.label_search_status_tableWidget_stk.setObjectName("label_search_status_tableWidget_stk")
        self.tabWidget.addTab(self.tab_stakeholder, "")
        self.tab_inventory = QtWidgets.QWidget()
        self.tab_inventory.setObjectName("tab_inventory")
        self.tableWidget_inv = QtWidgets.QTableWidget(self.tab_inventory)
        self.tableWidget_inv.setGeometry(QtCore.QRect(30, 210, 731, 271))
        self.tableWidget_inv.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_inv.setObjectName("tableWidget_inv")
        self.tableWidget_inv.setColumnCount(0)
        self.tableWidget_inv.setRowCount(0)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_inventory)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 20, 421, 171))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_Inv_01 = QtWidgets.QLabel(self.groupBox_2)
        self.label_Inv_01.setGeometry(QtCore.QRect(70, 20, 31, 16))
        self.label_Inv_01.setMinimumSize(QtCore.QSize(31, 0))
        self.label_Inv_01.setObjectName("label_Inv_01")
        self.lineEdit_inv_ItemID = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_inv_ItemID.setGeometry(QtCore.QRect(100, 20, 110, 22))
        self.lineEdit_inv_ItemID.setObjectName("lineEdit_inv_ItemID")
        self.lineEdit_inv_Manufacturer = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_inv_Manufacturer.setGeometry(QtCore.QRect(100, 80, 110, 22))
        self.lineEdit_inv_Manufacturer.setObjectName("lineEdit_inv_Manufacturer")
        self.label_Inv_03 = QtWidgets.QLabel(self.groupBox_2)
        self.label_Inv_03.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label_Inv_03.setMinimumSize(QtCore.QSize(81, 0))
        self.label_Inv_03.setObjectName("label_Inv_03")
        self.label_Inv_02 = QtWidgets.QLabel(self.groupBox_2)
        self.label_Inv_02.setGeometry(QtCore.QRect(50, 50, 41, 20))
        self.label_Inv_02.setMinimumSize(QtCore.QSize(41, 0))
        self.label_Inv_02.setObjectName("label_Inv_02")
        self.lineEdit_inv_ItemName = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_inv_ItemName.setGeometry(QtCore.QRect(100, 50, 110, 22))
        self.lineEdit_inv_ItemName.setObjectName("lineEdit_inv_ItemName")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(60, 110, 31, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_inv_ItemType = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_inv_ItemType.setGeometry(QtCore.QRect(100, 110, 110, 22))
        self.lineEdit_inv_ItemType.setObjectName("lineEdit_inv_ItemType")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(50, 140, 41, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_inv_ItemDetails = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_inv_ItemDetails.setGeometry(QtCore.QRect(100, 140, 291, 21))
        self.lineEdit_inv_ItemDetails.setObjectName("lineEdit_inv_ItemDetails")
        self.lineEdit_inv_AssetType = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_inv_AssetType.setGeometry(QtCore.QRect(280, 20, 110, 22))
        self.lineEdit_inv_AssetType.setObjectName("lineEdit_inv_AssetType")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(240, 20, 41, 16))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(230, 50, 40, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_inv_StockCount = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_inv_StockCount.setGeometry(QtCore.QRect(280, 50, 110, 22))
        self.lineEdit_inv_StockCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv_StockCount.setObjectName("lineEdit_inv_StockCount")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(220, 80, 51, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_inv_ReorderLevel = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_inv_ReorderLevel.setGeometry(QtCore.QRect(280, 80, 110, 22))
        self.lineEdit_inv_ReorderLevel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv_ReorderLevel.setObjectName("lineEdit_inv_ReorderLevel")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_inventory)
        self.groupBox_3.setGeometry(QtCore.QRect(620, 10, 141, 181))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 41, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 60, 41, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 80, 41, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 100, 41, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 120, 41, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 150, 41, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_inv_PricePurchaseBasic = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_inv_PricePurchaseBasic.setGeometry(QtCore.QRect(50, 20, 71, 22))
        self.lineEdit_inv_PricePurchaseBasic.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv_PricePurchaseBasic.setObjectName("lineEdit_inv_PricePurchaseBasic")
        self.lineEdit_inv_PricePurchaseAdd1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_inv_PricePurchaseAdd1.setGeometry(QtCore.QRect(50, 40, 71, 22))
        self.lineEdit_inv_PricePurchaseAdd1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv_PricePurchaseAdd1.setObjectName("lineEdit_inv_PricePurchaseAdd1")
        self.lineEdit_inv_PricePurchaseAdd2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_inv_PricePurchaseAdd2.setGeometry(QtCore.QRect(50, 60, 71, 22))
        self.lineEdit_inv_PricePurchaseAdd2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv_PricePurchaseAdd2.setObjectName("lineEdit_inv_PricePurchaseAdd2")
        self.lineEdit_inv_PricePurchaseAdd3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_inv_PricePurchaseAdd3.setGeometry(QtCore.QRect(50, 80, 71, 22))
        self.lineEdit_inv_PricePurchaseAdd3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv_PricePurchaseAdd3.setObjectName("lineEdit_inv_PricePurchaseAdd3")
        self.lineEdit_inv_PricePurchaseLess1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_inv_PricePurchaseLess1.setGeometry(QtCore.QRect(50, 100, 71, 22))
        self.lineEdit_inv_PricePurchaseLess1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv_PricePurchaseLess1.setObjectName("lineEdit_inv_PricePurchaseLess1")
        self.lineEdit_inv_PricePurchaseLess2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_inv_PricePurchaseLess2.setGeometry(QtCore.QRect(50, 120, 71, 22))
        self.lineEdit_inv_PricePurchaseLess2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv_PricePurchaseLess2.setObjectName("lineEdit_inv_PricePurchaseLess2")
        self.lineEdit_inv__PriceNetPurchase = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_inv__PriceNetPurchase.setGeometry(QtCore.QRect(50, 150, 71, 22))
        self.lineEdit_inv__PriceNetPurchase.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv__PriceNetPurchase.setObjectName("lineEdit_inv__PriceNetPurchase")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_inventory)
        self.groupBox_4.setGeometry(QtCore.QRect(470, 10, 141, 181))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(10, 40, 41, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(10, 60, 41, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(10, 80, 41, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(10, 100, 41, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(10, 120, 41, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setGeometry(QtCore.QRect(10, 150, 41, 16))
        self.label_30.setObjectName("label_30")
        self.lineEdit_inv_PriceSaleBasic = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_inv_PriceSaleBasic.setGeometry(QtCore.QRect(50, 20, 71, 22))
        self.lineEdit_inv_PriceSaleBasic.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv_PriceSaleBasic.setObjectName("lineEdit_inv_PriceSaleBasic")
        self.lineEdit_inv_PriceSaleAdd1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_inv_PriceSaleAdd1.setGeometry(QtCore.QRect(50, 40, 71, 22))
        self.lineEdit_inv_PriceSaleAdd1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv_PriceSaleAdd1.setObjectName("lineEdit_inv_PriceSaleAdd1")
        self.lineEdit_inv_PriceSaleAdd2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_inv_PriceSaleAdd2.setGeometry(QtCore.QRect(50, 60, 71, 22))
        self.lineEdit_inv_PriceSaleAdd2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv_PriceSaleAdd2.setObjectName("lineEdit_inv_PriceSaleAdd2")
        self.lineEdit_inv_PriceSaleAdd3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_inv_PriceSaleAdd3.setGeometry(QtCore.QRect(50, 80, 71, 22))
        self.lineEdit_inv_PriceSaleAdd3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv_PriceSaleAdd3.setObjectName("lineEdit_inv_PriceSaleAdd3")
        self.lineEdit_inv_PriceSaleLess1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_inv_PriceSaleLess1.setGeometry(QtCore.QRect(50, 100, 71, 22))
        self.lineEdit_inv_PriceSaleLess1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv_PriceSaleLess1.setObjectName("lineEdit_inv_PriceSaleLess1")
        self.lineEdit_inv_PriceSaleLess2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_inv_PriceSaleLess2.setGeometry(QtCore.QRect(50, 120, 71, 22))
        self.lineEdit_inv_PriceSaleLess2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv_PriceSaleLess2.setObjectName("lineEdit_inv_PriceSaleLess2")
        self.lineEdit_inv__PriceNetSale = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_inv__PriceNetSale.setGeometry(QtCore.QRect(50, 150, 71, 22))
        self.lineEdit_inv__PriceNetSale.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_inv__PriceNetSale.setObjectName("lineEdit_inv__PriceNetSale")
        self.label_inv_search = QtWidgets.QLabel(self.tab_inventory)
        self.label_inv_search.setGeometry(QtCore.QRect(30, 500, 60, 16))
        self.label_inv_search.setObjectName("label_inv_search")
        self.pushButton_search_prev_tableWidget_inv = QtWidgets.QPushButton(self.tab_inventory)
        self.pushButton_search_prev_tableWidget_inv.setGeometry(QtCore.QRect(430, 500, 51, 26))
        self.pushButton_search_prev_tableWidget_inv.setObjectName("pushButton_search_prev_tableWidget_inv")
        self.lineEdit_search_tableWidget_inv = QtWidgets.QLineEdit(self.tab_inventory)
        self.lineEdit_search_tableWidget_inv.setGeometry(QtCore.QRect(100, 500, 311, 22))
        self.lineEdit_search_tableWidget_inv.setObjectName("lineEdit_search_tableWidget_inv")
        self.label_search_status_tableWidget_inv = QtWidgets.QLabel(self.tab_inventory)
        self.label_search_status_tableWidget_inv.setGeometry(QtCore.QRect(550, 500, 60, 21))
        self.label_search_status_tableWidget_inv.setObjectName("label_search_status_tableWidget_inv")
        self.pushButton_search_next_tableWidget_inv = QtWidgets.QPushButton(self.tab_inventory)
        self.pushButton_search_next_tableWidget_inv.setGeometry(QtCore.QRect(490, 500, 51, 26))
        self.pushButton_search_next_tableWidget_inv.setObjectName("pushButton_search_next_tableWidget_inv")
        self.tabWidget.addTab(self.tab_inventory, "")
        self.tab_admin = QtWidgets.QWidget()
        self.tab_admin.setObjectName("tab_admin")
        self.tabWidget.addTab(self.tab_admin, "")
        self.tab_dashboard = QtWidgets.QWidget()
        self.tab_dashboard.setObjectName("tab_dashboard")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_dashboard)
        self.calendarWidget.setGeometry(QtCore.QRect(540, 40, 280, 173))
        self.calendarWidget.setObjectName("calendarWidget")
        self.tabWidget.addTab(self.tab_dashboard, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 882, 21))
        self.menubar.setObjectName("menubar")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        self.menuBackup = QtWidgets.QMenu(self.menubar)
        self.menuBackup.setObjectName("menuBackup")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(36, 36))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionDuplicateRecord = QtWidgets.QAction(MainWindow)
        self.actionDuplicateRecord.setIcon(icon1)
        self.actionDuplicateRecord.setObjectName("actionDuplicateRecord")
        self.actionNewRecord = QtWidgets.QAction(MainWindow)
        self.actionNewRecord.setIcon(icon)
        self.actionNewRecord.setObjectName("actionNewRecord")
        self.actionFilterRecord = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/Filter"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFilterRecord.setIcon(icon3)
        self.actionFilterRecord.setObjectName("actionFilterRecord")
        self.actionDeleteRecord = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/Delete"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteRecord.setIcon(icon4)
        self.actionDeleteRecord.setObjectName("actionDeleteRecord")
        self.actionRollback = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/Rollback"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRollback.setIcon(icon5)
        self.actionRollback.setObjectName("actionRollback")
        self.actionCommit = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/Commit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCommit.setIcon(icon6)
        self.actionCommit.setObjectName("actionCommit")
        self.actionTake_Backup = QtWidgets.QAction(MainWindow)
        self.actionTake_Backup.setObjectName("actionTake_Backup")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionRestore_Backup = QtWidgets.QAction(MainWindow)
        self.actionRestore_Backup.setObjectName("actionRestore_Backup")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.menuAction.addAction(self.actionNewRecord)
        self.menuAction.addAction(self.actionDuplicateRecord)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionSave)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionFilterRecord)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionDeleteRecord)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionRollback)
        self.menuAction.addAction(self.actionCommit)
        self.menuBackup.addAction(self.actionTake_Backup)
        self.menuBackup.addAction(self.actionRestore_Backup)
        self.menuBackup.addSeparator()
        self.menuBackup.addAction(self.actionExport)
        self.menuBackup.addAction(self.actionImport)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuAction.menuAction())
        self.menubar.addAction(self.menuBackup.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNewRecord)
        self.toolBar.addAction(self.actionDuplicateRecord)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFilterRecord)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCommit)
        self.toolBar.addAction(self.actionRollback)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tab_trans.setCurrentIndex(0)
        self.toolBox_trans_SalePurchase.setCurrentIndex(1)
        self.toolBox_trans_SalePurchase.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_Stk_StakeholderID, self.lineEdit_Stk_StakeholderName)
        MainWindow.setTabOrder(self.lineEdit_Stk_StakeholderName, self.lineEdit_Stk_ContactInfo)
        MainWindow.setTabOrder(self.lineEdit_Stk_ContactInfo, self.checkBox_IsCustomer)
        MainWindow.setTabOrder(self.checkBox_IsCustomer, self.checkBox_IsSupplier)
        MainWindow.setTabOrder(self.checkBox_IsSupplier, self.checkBox_IsEmployee)
        MainWindow.setTabOrder(self.checkBox_IsEmployee, self.lineEdit_Stk_AmountPayable)
        MainWindow.setTabOrder(self.lineEdit_Stk_AmountPayable, self.lineEdit_Stk_AmountReceivable)
        MainWindow.setTabOrder(self.lineEdit_Stk_AmountReceivable, self.lineEdit_Stk_ReminderNote)
        MainWindow.setTabOrder(self.lineEdit_Stk_ReminderNote, self.lineEdit_Stk_ID_ReminderDateTime)
        MainWindow.setTabOrder(self.lineEdit_Stk_ID_ReminderDateTime, self.lineEdit_Stk_Notes)
        MainWindow.setTabOrder(self.lineEdit_Stk_Notes, self.tableWidget_stk)
        MainWindow.setTabOrder(self.tableWidget_stk, self.lineEdit_trans_sale_terms)
        MainWindow.setTabOrder(self.lineEdit_trans_sale_terms, self.lineEdit_trans_sale_notes)
        MainWindow.setTabOrder(self.lineEdit_trans_sale_notes, self.calendarWidget)
        MainWindow.setTabOrder(self.calendarWidget, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.tableWidget_inv)
        MainWindow.setTabOrder(self.tableWidget_inv, self.lineEdit_inv_Manufacturer)
        MainWindow.setTabOrder(self.lineEdit_inv_Manufacturer, self.lineEdit_inv_ItemID)
        MainWindow.setTabOrder(self.lineEdit_inv_ItemID, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.lineEdit_inv_ItemName)
        MainWindow.setTabOrder(self.lineEdit_inv_ItemName, self.lineEdit_trans_sale_schedule)
        MainWindow.setTabOrder(self.lineEdit_trans_sale_schedule, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.tab_trans)
        MainWindow.setTabOrder(self.tab_trans, self.lineEdit_trans_sale_StakeholderName)
        MainWindow.setTabOrder(self.lineEdit_trans_sale_StakeholderName, self.tableWidget_transaction)
        MainWindow.setTabOrder(self.tableWidget_transaction, self.lineEdit_trans_sale_quantity)
        MainWindow.setTabOrder(self.lineEdit_trans_sale_quantity, self.lineEdit_trans_sale_ItemID)
        MainWindow.setTabOrder(self.lineEdit_trans_sale_ItemID, self.lineEdit_trans_sale_Item_details)
        MainWindow.setTabOrder(self.lineEdit_trans_sale_Item_details, self.lineEdit_trans_sale_credit)
        MainWindow.setTabOrder(self.lineEdit_trans_sale_credit, self.lineEdit_trans_sale_unit)
        MainWindow.setTabOrder(self.lineEdit_trans_sale_unit, self.lineEdit_trans_sale_rate)
        MainWindow.setTabOrder(self.lineEdit_trans_sale_rate, self.lineEdit_trans_sale_total)
        MainWindow.setTabOrder(self.lineEdit_trans_sale_total, self.lineEdit_trans_sale_cash)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hisaab-Kitaab V1"))
        self.label_Tab_Title.setText(_translate("MainWindow", "Transaction"))
        self.label_trans_sale_12.setText(_translate("MainWindow", "Invoice #"))
        self.label_trans_sale_14.setText(_translate("MainWindow", "Date/Time"))
        self.label_trans_sale_01.setText(_translate("MainWindow", "Stakeholder"))
        self.pushButton_trans_addInvoice_2.setToolTip(_translate("MainWindow", "Show Stakeholders"))
        self.pushButton_trans_addInvoice_2.setStatusTip(_translate("MainWindow", "Show Stakeholders"))
        self.pushButton_trans_addInvoice_2.setWhatsThis(_translate("MainWindow", "Show Stakeholders"))
        self.pushButton_trans_addInvoice_2.setText(_translate("MainWindow", "*"))
        self.label_trans_sale_13.setText(_translate("MainWindow", "Type"))
        self.label_trans_sale_15.setText(_translate("MainWindow", "TransID"))
        self.label_trans_sale_02.setText(_translate("MainWindow", "Item"))
        self.label_trans_sale_03.setText(_translate("MainWindow", "Details"))
        self.lineEdit_trans_sale_quantity.setText(_translate("MainWindow", "0"))
        self.label_trans_sale_5.setText(_translate("MainWindow", "Unit"))
        self.label_trans_sale_4.setText(_translate("MainWindow", "Quantity"))
        self.lineEdit_trans_sale_total.setText(_translate("MainWindow", "0"))
        self.label_trans_sale_7.setText(_translate("MainWindow", "Total "))
        self.label_trans_sale_6.setText(_translate("MainWindow", "Rate"))
        self.lineEdit_trans_sale_rate.setText(_translate("MainWindow", "0"))
        self.lineEdit_trans_sale_cash.setText(_translate("MainWindow", "0"))
        self.label_trans_sale_21.setText(_translate("MainWindow", "Cash"))
        self.label_trans_sale_9.setText(_translate("MainWindow", "Schedule"))
        self.lineEdit_trans_sale_credit.setText(_translate("MainWindow", "0"))
        self.label_trans_sale_8.setText(_translate("MainWindow", "Credit"))
        self.label_trans_sale_10.setText(_translate("MainWindow", "Terms"))
        self.label_trans_sale_11.setText(_translate("MainWindow", "Notes"))
        self.pushButton_trans_addInvoice_3.setToolTip(_translate("MainWindow", "Show Items"))
        self.pushButton_trans_addInvoice_3.setStatusTip(_translate("MainWindow", "Show Items"))
        self.pushButton_trans_addInvoice_3.setWhatsThis(_translate("MainWindow", "Show Items"))
        self.pushButton_trans_addInvoice_3.setText(_translate("MainWindow", "*"))
        self.toolBox_trans_SalePurchase.setItemText(self.toolBox_trans_SalePurchase.indexOf(self.page_Invoice), _translate("MainWindow", "Invoice"))
        self.toolBox_trans_SalePurchase.setItemText(self.toolBox_trans_SalePurchase.indexOf(self.page_History), _translate("MainWindow", "History"))
        self.tab_trans.setTabText(self.tab_trans.indexOf(self.tab_trans_Sale), _translate("MainWindow", "Sale/Purchase"))
        self.tab_trans.setTabText(self.tab_trans.indexOf(self.tab_trans_General), _translate("MainWindow", "General"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.tableWidget_transaction.setSortingEnabled(True)
        self.tab_trans.setTabText(self.tab_trans.indexOf(self.tab_trans_All), _translate("MainWindow", "All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Transaction), _translate("MainWindow", "Transaction"))
        self.tableWidget_stk.setSortingEnabled(True)
        self.label_Stk_01.setText(_translate("MainWindow", "ID"))
        self.checkBox_IsCustomer.setText(_translate("MainWindow", "Customer"))
        self.lineEdit_Stk_AmountPayable.setText(_translate("MainWindow", "0"))
        self.checkBox_IsSupplier.setText(_translate("MainWindow", "Supplier"))
        self.label_Stk_10.setText(_translate("MainWindow", "Notes"))
        self.label_Stk_12.setText(_translate("MainWindow", "Schedule"))
        self.label_Stk_11.setText(_translate("MainWindow", "Reminder"))
        self.label_Stk_03.setText(_translate("MainWindow", "Contact"))
        self.label_Stk_08.setText(_translate("MainWindow", "Payable"))
        self.checkBox_IsEmployee.setText(_translate("MainWindow", "Employee"))
        self.label_Stk_02.setText(_translate("MainWindow", "Name"))
        self.lineEdit_Stk_AmountReceivable.setText(_translate("MainWindow", "0"))
        self.label_Stk_09.setText(_translate("MainWindow", "Receivable"))
        self.label_stk_search.setText(_translate("MainWindow", "Filter"))
        self.pushButton_search_prev_tableWidget_stk.setText(_translate("MainWindow", "<"))
        self.pushButton_search_next_tableWidget_stk.setText(_translate("MainWindow", ">"))
        self.label_search_status_tableWidget_stk.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_stakeholder), _translate("MainWindow", "Stakeholder"))
        self.tableWidget_inv.setSortingEnabled(True)
        self.label_Inv_01.setText(_translate("MainWindow", "ID"))
        self.label_Inv_03.setText(_translate("MainWindow", "Manufacturer"))
        self.label_Inv_02.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Type"))
        self.label_5.setText(_translate("MainWindow", "Details"))
        self.label_6.setText(_translate("MainWindow", "Asset"))
        self.label_8.setText(_translate("MainWindow", "Count"))
        self.label_9.setText(_translate("MainWindow", "ReOrder"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Purchase"))
        self.label_10.setText(_translate("MainWindow", "Basic"))
        self.label_11.setText(_translate("MainWindow", "Add:1"))
        self.label_12.setText(_translate("MainWindow", "Add:2"))
        self.label_13.setText(_translate("MainWindow", "Add:3"))
        self.label_14.setText(_translate("MainWindow", "Less:1"))
        self.label_15.setText(_translate("MainWindow", "Less:2"))
        self.label_16.setText(_translate("MainWindow", "Net"))
        self.lineEdit_inv_PricePurchaseBasic.setText(_translate("MainWindow", "0"))
        self.lineEdit_inv_PricePurchaseAdd1.setText(_translate("MainWindow", "0"))
        self.lineEdit_inv_PricePurchaseAdd2.setText(_translate("MainWindow", "0"))
        self.lineEdit_inv_PricePurchaseAdd3.setText(_translate("MainWindow", "0"))
        self.lineEdit_inv_PricePurchaseLess1.setText(_translate("MainWindow", "0"))
        self.lineEdit_inv_PricePurchaseLess2.setText(_translate("MainWindow", "0"))
        self.lineEdit_inv__PriceNetPurchase.setText(_translate("MainWindow", "0"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Sale"))
        self.label_24.setText(_translate("MainWindow", "Basic"))
        self.label_25.setText(_translate("MainWindow", "Add:1"))
        self.label_26.setText(_translate("MainWindow", "Add:2"))
        self.label_27.setText(_translate("MainWindow", "Add:3"))
        self.label_28.setText(_translate("MainWindow", "Less:1"))
        self.label_29.setText(_translate("MainWindow", "Less:2"))
        self.label_30.setText(_translate("MainWindow", "Net"))
        self.lineEdit_inv_PriceSaleBasic.setText(_translate("MainWindow", "0"))
        self.lineEdit_inv_PriceSaleAdd1.setText(_translate("MainWindow", "0"))
        self.lineEdit_inv_PriceSaleAdd2.setText(_translate("MainWindow", "0"))
        self.lineEdit_inv_PriceSaleAdd3.setText(_translate("MainWindow", "0"))
        self.lineEdit_inv_PriceSaleLess1.setText(_translate("MainWindow", "0"))
        self.lineEdit_inv_PriceSaleLess2.setText(_translate("MainWindow", "0"))
        self.lineEdit_inv__PriceNetSale.setText(_translate("MainWindow", "0"))
        self.label_inv_search.setText(_translate("MainWindow", "Filter"))
        self.pushButton_search_prev_tableWidget_inv.setText(_translate("MainWindow", "<"))
        self.label_search_status_tableWidget_inv.setText(_translate("MainWindow", "0"))
        self.pushButton_search_next_tableWidget_inv.setText(_translate("MainWindow", ">"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_inventory), _translate("MainWindow", "Inventory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_admin), _translate("MainWindow", "Admin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dashboard), _translate("MainWindow", "Dashboard"))
        self.menuAction.setTitle(_translate("MainWindow", "Action"))
        self.menuBackup.setTitle(_translate("MainWindow", "Backup"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionDuplicateRecord.setText(_translate("MainWindow", "Duplicate"))
        self.actionDuplicateRecord.setToolTip(_translate("MainWindow", "Duplicate"))
        self.actionDuplicateRecord.setStatusTip(_translate("MainWindow", "Duplicate"))
        self.actionDuplicateRecord.setWhatsThis(_translate("MainWindow", "Duplicate"))
        self.actionNewRecord.setText(_translate("MainWindow", "New"))
        self.actionFilterRecord.setText(_translate("MainWindow", "Filter"))
        self.actionFilterRecord.setToolTip(_translate("MainWindow", "Filter Records"))
        self.actionFilterRecord.setStatusTip(_translate("MainWindow", "Filter Records"))
        self.actionFilterRecord.setWhatsThis(_translate("MainWindow", "Filter Records"))
        self.actionDeleteRecord.setText(_translate("MainWindow", "Delete"))
        self.actionRollback.setText(_translate("MainWindow", "Rollback"))
        self.actionCommit.setText(_translate("MainWindow", "Commit"))
        self.actionTake_Backup.setText(_translate("MainWindow", "Take Backup"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionRestore_Backup.setText(_translate("MainWindow", "Restore Backup"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
import res_main_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
